; DO NOT EDIT - This file is generated by `cargo xtask gen-crates`
; To modify, edit the source in grammars/tree-sitter-*/queries/
; or add extra_injections in grammars/tree-sitter-*/grammar-crate-config.toml

; Default CSS in <style> tags (no lang attribute)
((style_element
  (raw_text) @injection.content)
 (#set! injection.language "css"))

; SCSS/PostCSS/etc when lang attribute is set
((style_element
  (start_tag
    (attribute
      (attribute_name) @_attr
      (quoted_attribute_value
        (attribute_value) @_lang)))
  (raw_text) @injection.content)
  (#eq? @_attr "lang")
  (#any-of? @_lang "scss" "postcss" "less" "stylus")
  (#set! injection.language "scss"))

; Default JavaScript in <script> tags (no lang attribute)
((script_element
  (raw_text) @injection.content)
  (#set! injection.language "javascript"))

; JavaScript in Svelte template expressions like {name}, {#if condition}, etc.
((svelte_raw_text) @injection.content
  (#set! injection.language "javascript"))

((script_element
  (start_tag
    (attribute
      (attribute_name) @_attr
      (quoted_attribute_value
        (attribute_value) @_lang)))
  (raw_text) @injection.content)
  (#eq? @_attr "lang")
  (#any-of? @_lang "ts" "typescript")
  (#set! injection.language "typescript"))

((element
  (start_tag
    (attribute
      (attribute_name) @_attr
      (quoted_attribute_value
        (attribute_value) @injection.language)))
  (text) @injection.content)
  (#eq? @_attr "lang")
  (#eq? @injection.language "pug"))