; DO NOT EDIT - This file is generated by `cargo xtask gen-crates`
; To modify, edit the source in grammars/tree-sitter-*/queries/
; or add extra_injections in grammars/tree-sitter-*/grammar-crate-config.toml

