//! Auto-generated by xtask generate-demo - DO NOT EDIT MANUALLY
//!
//! This file is generated from info.toml files in crates/arborium-*

use arborium::{
    html,
    tree_sitter_highlight::{HighlightConfiguration, Highlighter},
    HIGHLIGHT_NAMES,
};
use wasm_bindgen::prelude::*;

/// Helper to create a HighlightConfiguration from a grammar module
macro_rules! make_config {
    ($lang:ident, $name:expr) => {{
        HighlightConfiguration::new(
            arborium::$lang::language().into(),
            $name,
            arborium::$lang::HIGHLIGHTS_QUERY,
            arborium::$lang::INJECTIONS_QUERY,
            arborium::$lang::LOCALS_QUERY,
        )
    }};
}

/// Get a highlight configuration for the given language
fn get_config(language: &str) -> Option<Result<HighlightConfiguration, arborium::tree_sitter::QueryError>> {
    match language {
        "ada" => Some(make_config!(lang_ada, "ada")),
        "agda" => Some(make_config!(lang_agda, "agda")),
        "asm" | "assembly" => Some(make_config!(lang_asm, "asm")),
        "awk" => Some(make_config!(lang_awk, "awk")),
        "bash" | "sh" | "shell" => Some(make_config!(lang_bash, "bash")),
        "batch" | "bat" | "cmd" => Some(make_config!(lang_batch, "batch")),
        "c" | "h" => Some(make_config!(lang_c, "c")),
        "c-sharp" | "cs" | "csharp" => Some(make_config!(lang_c_sharp, "c-sharp")),
        "caddy" => Some(make_config!(lang_caddy, "caddy")),
        "capnp" => Some(make_config!(lang_capnp, "capnp")),
        "clojure" | "clj" => Some(make_config!(lang_clojure, "clojure")),
        "cmake" => Some(make_config!(lang_cmake, "cmake")),
        "commonlisp" | "lisp" | "cl" => Some(make_config!(lang_commonlisp, "commonlisp")),
        "cpp" | "c++" | "cxx" | "hpp" => Some(make_config!(lang_cpp, "cpp")),
        "css" => Some(make_config!(lang_css, "css")),
        "d" | "dlang" => Some(make_config!(lang_d, "d")),
        "dart" => Some(make_config!(lang_dart, "dart")),
        "devicetree" => Some(make_config!(lang_devicetree, "devicetree")),
        "diff" | "patch" => Some(make_config!(lang_diff, "diff")),
        "dockerfile" | "docker" => Some(make_config!(lang_dockerfile, "dockerfile")),
        "dot" => Some(make_config!(lang_dot, "dot")),
        "elisp" | "emacs-lisp" | "el" => Some(make_config!(lang_elisp, "elisp")),
        "elixir" | "ex" | "exs" => Some(make_config!(lang_elixir, "elixir")),
        "elm" => Some(make_config!(lang_elm, "elm")),
        "erlang" | "erl" => Some(make_config!(lang_erlang, "erlang")),
        "fish" => Some(make_config!(lang_fish, "fish")),
        "fsharp" | "fs" | "f#" => Some(make_config!(lang_fsharp, "fsharp")),
        "gleam" => Some(make_config!(lang_gleam, "gleam")),
        "glsl" | "vert" | "frag" => Some(make_config!(lang_glsl, "glsl")),
        "go" | "golang" => Some(make_config!(lang_go, "go")),
        "graphql" | "gql" => Some(make_config!(lang_graphql, "graphql")),
        "haskell" | "hs" => Some(make_config!(lang_haskell, "haskell")),
        "hcl" | "terraform" | "tf" => Some(make_config!(lang_hcl, "hcl")),
        "hlsl" => Some(make_config!(lang_hlsl, "hlsl")),
        "html" | "htm" => Some(make_config!(lang_html, "html")),
        "ini" | "conf" | "cfg" => Some(make_config!(lang_ini, "ini")),
        "java" => Some(make_config!(lang_java, "java")),
        "javascript" | "js" | "jsx" | "mjs" | "cjs" => Some(make_config!(lang_javascript, "javascript")),
        "jinja2" | "jinja" | "j2" => Some(make_config!(lang_jinja2, "jinja2")),
        "jq" => Some(make_config!(lang_jq, "jq")),
        "json" | "jsonc" => Some(make_config!(lang_json, "json")),
        "julia" | "jl" => Some(make_config!(lang_julia, "julia")),
        "kdl" => Some(make_config!(lang_kdl, "kdl")),
        "kotlin" | "kt" | "kts" => Some(make_config!(lang_kotlin, "kotlin")),
        "lean" => Some(make_config!(lang_lean, "lean")),
        "lua" => Some(make_config!(lang_lua, "lua")),
        "matlab" | "m" => Some(make_config!(lang_matlab, "matlab")),
        "meson" => Some(make_config!(lang_meson, "meson")),
        "nginx" => Some(make_config!(lang_nginx, "nginx")),
        "ninja" => Some(make_config!(lang_ninja, "ninja")),
        "nix" => Some(make_config!(lang_nix, "nix")),
        "objc" | "objective-c" | "mm" => Some(make_config!(lang_objc, "objc")),
        "ocaml" | "ml" => Some(make_config!(lang_ocaml, "ocaml")),
        "perl" | "pl" | "pm" => Some(make_config!(lang_perl, "perl")),
        "php" => Some(make_config!(lang_php, "php")),
        "powershell" | "ps1" | "pwsh" => Some(make_config!(lang_powershell, "powershell")),
        "prolog" => Some(make_config!(lang_prolog, "prolog")),
        "python" | "py" | "py3" | "python3" => Some(make_config!(lang_python, "python")),
        "query" | "scm" => Some(make_config!(lang_query, "query")),
        "r" | "rlang" => Some(make_config!(lang_r, "r")),
        "rescript" | "res" => Some(make_config!(lang_rescript, "rescript")),
        "ron" => Some(make_config!(lang_ron, "ron")),
        "ruby" | "rb" => Some(make_config!(lang_ruby, "ruby")),
        "rust" | "rs" => Some(make_config!(lang_rust, "rust")),
        "scala" => Some(make_config!(lang_scala, "scala")),
        "scheme" => Some(make_config!(lang_scheme, "scheme")),
        "scss" | "sass" => Some(make_config!(lang_scss, "scss")),
        "sparql" | "rq" => Some(make_config!(lang_sparql, "sparql")),
        "sql" | "mysql" | "postgresql" | "postgres" | "sqlite" => Some(make_config!(lang_sql, "sql")),
        "ssh-config" => Some(make_config!(lang_ssh_config, "ssh-config")),
        "starlark" | "bzl" | "bazel" => Some(make_config!(lang_starlark, "starlark")),
        "svelte" => Some(make_config!(lang_svelte, "svelte")),
        "swift" => Some(make_config!(lang_swift, "swift")),
        "textproto" | "pbtxt" | "textpb" => Some(make_config!(lang_textproto, "textproto")),
        "thrift" => Some(make_config!(lang_thrift, "thrift")),
        "tlaplus" | "tla" => Some(make_config!(lang_tlaplus, "tlaplus")),
        "toml" => Some(make_config!(lang_toml, "toml")),
        "tsx" => Some(make_config!(lang_tsx, "tsx")),
        "typescript" | "ts" | "mts" | "cts" => Some(make_config!(lang_typescript, "typescript")),
        "typst" | "typ" => Some(make_config!(lang_typst, "typst")),
        "uiua" | "ua" => Some(make_config!(lang_uiua, "uiua")),
        "vb" | "vbnet" | "visualbasic" => Some(make_config!(lang_vb, "vb")),
        "verilog" | "v" | "sv" | "systemverilog" => Some(make_config!(lang_verilog, "verilog")),
        "vhdl" | "vhd" => Some(make_config!(lang_vhdl, "vhdl")),
        "vue" => Some(make_config!(lang_vue, "vue")),
        "x86asm" | "nasm" | "x86" => Some(make_config!(lang_x86asm, "x86asm")),
        "xml" | "xsl" | "xslt" | "svg" => Some(make_config!(lang_xml, "xml")),
        "yaml" | "yml" => Some(make_config!(lang_yaml, "yaml")),
        "yuri" => Some(make_config!(lang_yuri, "yuri")),
        "zig" => Some(make_config!(lang_zig, "zig")),
        _ => None,
    }
}

/// Highlight source code and return HTML
#[wasm_bindgen]
pub fn highlight(language: &str, source: &str) -> Result<String, JsValue> {
    let config_result = get_config(language);
    let mut config = config_result
        .ok_or_else(|| JsValue::from_str(&format!("Unsupported language: {}", language)))?
        .map_err(|e| JsValue::from_str(&format!("Grammar error: {}", e)))?;

    // Configure highlight names
    let names: Vec<String> = HIGHLIGHT_NAMES.iter().map(|s| s.to_string()).collect();
    config.configure(&names);

    // Pre-create configs for common injection targets (JS, CSS, etc.)
    let mut injection_configs: std::collections::HashMap<&str, HighlightConfiguration> = std::collections::HashMap::new();
    
    // JavaScript (for HTML <script> tags)
    if let Some(Ok(mut js_config)) = get_config("javascript") {
        js_config.configure(&names);
        injection_configs.insert("javascript", js_config);
    }
    
    // CSS (for HTML <style> tags)
    if let Some(Ok(mut css_config)) = get_config("css") {
        css_config.configure(&names);
        injection_configs.insert("css", css_config);
    }

    let mut highlighter = Highlighter::new();
    let mut output = Vec::new();

    html::render(&mut output, &mut highlighter, &config, source, |lang| {
        injection_configs.get(lang)
    })
        .map_err(|e| JsValue::from_str(&format!("Render error: {}", e)))?;

    String::from_utf8(output).map_err(|e| JsValue::from_str(&format!("UTF-8 error: {}", e)))
}

/// Get list of supported languages
#[wasm_bindgen]
pub fn supported_languages() -> Vec<JsValue> {
    vec![
        "ada",
        "agda",
        "asm",
        "awk",
        "bash",
        "batch",
        "c",
        "c-sharp",
        "caddy",
        "capnp",
        "clojure",
        "cmake",
        "commonlisp",
        "cpp",
        "css",
        "d",
        "dart",
        "devicetree",
        "diff",
        "dockerfile",
        "dot",
        "elisp",
        "elixir",
        "elm",
        "erlang",
        "fish",
        "fsharp",
        "gleam",
        "glsl",
        "go",
        "graphql",
        "haskell",
        "hcl",
        "hlsl",
        "html",
        "ini",
        "java",
        "javascript",
        "jinja2",
        "jq",
        "json",
        "julia",
        "kdl",
        "kotlin",
        "lean",
        "lua",
        "matlab",
        "meson",
        "nginx",
        "ninja",
        "nix",
        "objc",
        "ocaml",
        "perl",
        "php",
        "powershell",
        "prolog",
        "python",
        "query",
        "r",
        "rescript",
        "ron",
        "ruby",
        "rust",
        "scala",
        "scheme",
        "scss",
        "sparql",
        "sql",
        "ssh-config",
        "starlark",
        "svelte",
        "swift",
        "textproto",
        "thrift",
        "tlaplus",
        "toml",
        "tsx",
        "typescript",
        "typst",
        "uiua",
        "vb",
        "verilog",
        "vhdl",
        "vue",
        "x86asm",
        "xml",
        "yaml",
        "yuri",
        "zig",
    ]
    .into_iter()
    .map(JsValue::from_str)
    .collect()
}

/// Get the highlight class names
#[wasm_bindgen]
pub fn highlight_names() -> Vec<JsValue> {
    HIGHLIGHT_NAMES
        .iter()
        .map(|s| JsValue::from_str(s))
        .collect()
}
